pledg_sylius_payment_plugin_webhook_notification:
    path: /notification
    methods: [GET, POST]
    defaults:
        _controller: Pledg\SyliusPaymentPlugin\Controller\Webhook\NotificationAction

pledg_sylius_payment_plugin_webhook_error_notification:
    path: /notification/error
    methods: [GET, POST]
    defaults:
        _controller: Pledg\SyliusPaymentPlugin\Controller\Webhook\NotificationAction

pledg_sylius_payment_plugin_shop_simulate_payment:
    path: /shop/simulate-payment/{code}
    defaults:
        _controller: Pledg\SyliusPaymentPlugin\Controller\Shop\SimulatePaymentAction

pledg_sylius_payment_plugin_shop_simulate_payment_amount:
    path: /shop/simulate-payment/{code}/{amountCents}
    requirements:
        amountCents: '\d+'
    defaults:
        _controller: Pledg\SyliusPaymentPlugin\Controller\Shop\SimulatePaymentForAmountAction

pledg_sylius_payment_plugin_widget_simulate_batch:
    path: /widget/simulate-batch
    methods: [POST]
    defaults:
        _controller: Pledg\SyliusPaymentPlugin\Controller\Shop\SimulateWidgetAction

pledg_sylius_payment_plugin_shop_recalculate_total:
    path: /shop/recalculate-total/{fees}
    defaults:
        _controller: Pledg\SyliusPaymentPlugin\Controller\Shop\RecalculateTotalAction
